export const TRADING_CONFIG = {
  INITIAL_WALLET_BALANCE_SOL: 300,
  POLLING_INTERVAL_MS: 3000,
  TARGET_TOKEN_ADDRESS: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263", // BONK token
  TARGET_TOKEN_SYMBOL: "BONK",
  BASE_TOKEN_SYMBOL: "SOL"
};
